### ISSUE TITLE
Domain renewal using cart does not work as expected

### ISSUE THREAD

**Issue by RevZer0** [rrpproxy/whmcs-rrpproxy-registrar#25]
When I tried to renew recently created domain it won't renewed on RRPProxy side but renewed in WHMCS.
Small digging into code gave me some clues why it happens.

First of all this block of code of renewal function:
```php
$response = $api->call('StatusDomain', ['domain' => $params['domainname']]);
$date = $response['property']['registrationexpirationdate'][0];
$expirationDate = new DateTime(date('Y-m-d', strtotime($date)));
$currentDate = new DateTime(date('Y-m-d'));
$diff = $currentDate->diff($expirationDate);
$years = round($diff->days / 365);
if ($years > 0) {
     $params["regperiod"] -= $years;
}
```
Assume that client want to renew domain for 1 year (e.g  $params["regperiod"] === 1)
According to this logic domain will be renewed only if it has less than 182 days before expiration (`round(182/365) === 0`)
In other cases `regperiod` param becomes 0 and lead us to another problematic block of code.

```php
if ($params["regperiod"] > 0) {
    if (!$zoneInfo->supports_renewals) {
        $api->call('SetDomainRenewalMode', ['domain' => $params['domainname'], 'renewalmode' => 'RENEWONCE']);
    } else {
        $api->call('RenewDomain', ['domain' => $params['domainname'], 'period' => $params["regperiod"], 'expiration' => $domain->expirydate->year]);
    }
}
return ['success' => true];
```
Even if no API calls where performed (`false === ($params["regperiod"] > 0)`) function return `success` to the WHMCS. After that WHMCS updates inner domain service expiration date and billing due date.

Would be appreciate if you fix this or I can make PR if we will found suitable solution.

**Comment by h9k** [comment]
Thanks for reporting.

We decided to remove the logic that potentially lowers the amount of renewal years.
The intentions were good but the drawbacks outweigh the benefit.
So the module will now renew exactly as commanded by WHMCS.

As long as the reseller has autorenew disabled (which we recommend) and just lets domains expire if customers don't pay, there should be no issues. There are grace and redemption fees since a couple of WHMCS releases, so we recommend using that feature as well.
