### ISSUE TITLE
how to bulk change the domain setting in WHMCS panel

### ISSUE THREAD

**Issue by jsjcjsjc** [rrpproxy/whmcs-rrpproxy-registrar#54]
I really do not want to click them one by one....
is it possible to bulk change the domain setting in WHMCS panel
Thanks
![avatar](https://s3.jpg.cm/2021/08/28/IH6oDG.png)

**Comment by Remitur** [comment]
You can easily do it with a SQL query in phpmyadmin...

**Comment by jsjcjsjc** [comment]
> You can easily do it with a SQL query in phpmyadmin...

Thanks for your kind help.
But i am not familiar with phpmyadmin, could you please show me how to do it ?
And I still think it is a good new Features ;-)

**Comment by Remitur** [comment]
If you're managing a WHMCS system without a basic knowledge of MySQL, you're walking on very thin ice...
I suggest you task the help of anyone with basic skills in MySQL, and see what he does to learn... it's not difficult (much more difficult to explain than to do), but any mistake may be very dangerous.

Or you can install this free add on: https://www.resellerclub-mods.com/whmcs/free-resellerclub-tools-addon.php
(It was written for Resellerclub, but has a lot of features working for any registrar module... and there's also the bulk TLD setting you're looking for)

**Comment by h9k** [comment]
I suggest you use the `Utilities > Registrar TLD Sync` feature in the WHMCS Admin Area, which this module supports.
This will automatically set the registrar to keysystems and enable EPP code for domains that support it.

To enable DNS Management and Email Forwarding for all, the SQL query would be
```mysql
UPDATE tbldomainpricing SET dnsmanagement = 1, emailforwarding = 1 WHERE autoreg = 'keysystems'
```

I advise against enabling ID protection for all domains, as not all domains support it. Unfortunately, WHMCS does not provide a way to set this in the TLD Sync, but we actually store this information in our own table for future use. And the future is now :)
To sync that info with the domain pricing, you could execute this query
```mysql
UPDATE tbldomainpricing AS p
JOIN mod_rrpproxy_zones AS z ON CONCAT(".", z.zone) = p.extension
SET p.idprotection = z.id_protection, p.eppcode = z.epp_required
WHERE p.autoreg = 'keysystems'
```

Hope this helps!
I think we should consider automating this via a workaround, so I will leave this issue open for now for internal discussion.

**Comment by papakai** [comment]
@jsjcjsjc thanks for addressing. Yes, the missing possibility in WHMCS for updating such things nicely in bulk, is really bad. Like @Remitur already forwarded, often the easiest and fastest way is to update things directly in the DB and I fully agree - you need to understand what you're doing, otherwise your system's data consistency may break.

@h9k yes, definitely. The HEXONET/ispapi addon already supports syncing the id protection addon where it is supported. regarding dns management & email forwarding - this is basically supported for all TLDs as these addons are just bound to internal DNSZones. eMail Forwarding works just with active dns management. dns management cares about creating the underlying internal DNSZone.

This is noted down in our backlog, we will include this in the upcoming module rewrite. It will take a while, but will finally be supported.
