### ISSUE TITLE
one year price of .to/.gr/.hu 

### ISSUE THREAD

**Issue by jsjcjsjc** [rrpproxy/whmcs-rrpproxy-registrar#89]
Hi
it looks like the price of .to/.gr/.hu  not available in one year, at lease two year, is this bug or ok ?
Thanks in advance

**Comment by papakai** [comment]
Hi @jsjcjsjc,

Let us have an eye on the TLD documentation:

* https://wiki.rrpproxy.net/domains/tlds/gr
* https://wiki.rrpproxy.net/domains/tlds/hu
* https://wiki.rrpproxy.net/domains/tlds/to

You'll find the Registration Periods and Renewal Periods listed at right.
WHMCS allows ONLY to import a single list of periods for registration AND renewal.
That's the main reason for such supported terms "issues" in WHMCS.

**regarding .gr**
Just a 2 year registration term is supported, which is what we have to return then to WHMCS in the Registrar TLD Sync.
Technically, .gr is supporting further renewals terms, but whmcs isn't technically supporting the import of different list of terms to distinguish between registration and renewal which would be very useful.

**regarding .hu**
.hu supports a 2Y registration term, which is what is getting returned to WHMCS over registrar TLD Sync. But finally only supporting a 1Y renewal term... I expect WHMCS to autorenew with a 2Y term though, which is not supported as .HU only supports this 1Y renewal term. This would lead to a support case on our end imho. I'll create a task for getting clarification on .hu. If the documentation is right, this is a major issue when it comes to renewals and eventually a blocker for offering .hu over whmcs.

**regarding .to**
You notice very different lists of periods in the documentation. 1Y registration isn't supported, that's why importing the 1Y renewal term isn't possible over WHMCS.

My own opinion: The pricing import in WHMCS comes with some design issues, this is one of them.

Thanks for pointing on .hu, I'll keep you posted on that matter.
I hope you were able to follow the technical explanation. Otherwise feel free to follow-up.

Best
Kai

**Comment by papakai** [comment]
Hi @jsjcjsjc,

yes, the .HU periods are correct and a result of our underlying partner/provider.
You might have an eye on the [HEXONET registrar module](https://github.com/hexonet/whmcs-ispapi-registrar/releases) that we offer as well. There, the 1Y term is supported for registration and renewal for .HU and .TO as well, but also not for .GR.

Hope that helps!
Best
Kai

**Comment by papakai** [comment]
Hey @jsjcjsjc,

the underlying provider for .HU confirmed, that they will be introducing the 1Y registration term for .HU in short. Expect therefore the 1Y term to be upcoming soon for RRPproxy as well.

Best
Kai
